// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"
	"log"
	neturl "net/url"

	"github.com/chaitin/workspace-cli/config"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/chaitin/workspace-cli/products/xray/client"
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

var (
	// debug flag indicating that cli should output debug logs
	debug bool

	// dry run flag
	dryRun bool

	// runtime config injected by the root command
	runtimeCfg runtimeProductConfig
)

type runtimeProductConfig struct {
	URL    string `yaml:"url"`
	APIKey string `yaml:"api_key"`
}

// logDebugf writes debug log to stdout
func logDebugf(format string, v ...any) {
	if !debug {
		return
	}
	log.Printf(format, v...)
}

// depth of recursion to construct model flags
var maxDepth int = 5

// makeClient constructs a client object
func makeClient(cmd *cobra.Command, _ []string) (*client.OPENAPI, error) {
	scheme, hostname, basePath, err := resolveServerConfig(cmd)
	if err != nil {
		return nil, err
	}

	r := httptransport.New(hostname, basePath, []string{scheme})
	r.SetDebug(debug)
	// set custom producer and consumer to use the default ones

	r.Consumers["application/json"] = runtime.JSONConsumer()

	// warning: consumes multipart/form-data is not supported by go-swagger cli yet

	// warning: produces application/octet-stream is not supported by go-swagger cli yet
	r.Producers["application/json"] = runtime.JSONProducer()

	auth, err := makeAuthInfoWriter(cmd)
	if err != nil {
		return nil, err
	}
	r.DefaultAuthentication = auth

	appCli := client.New(r, strfmt.Default)
	logDebugf("Server url: %v://%v", scheme, hostname)

	return appCli, nil
}

// MakeCommand returns the xray subcommand
func MakeCommand() (*cobra.Command, error) {
	// Use "xray" as the command name for subcommand usage
	rootCmd := &cobra.Command{
		Use: "xray",
	}

	rootCmd.PersistentFlags().String("url", "", "API URL (e.g. https://api.example.com/api/v2)")

	// configure debug flag
	rootCmd.PersistentFlags().BoolVar(&debug, "debug", false, "output debug logs")

	// register security flags
	if err := registerAuthInoWriterFlags(rootCmd); err != nil {
		return nil, err
	}

	// add all operation groups
	c0, err := makeGroupOfOperationsAssetPropertyCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c0)
	c1, err := makeGroupOfOperationsAuditLogCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c1)
	c2, err := makeGroupOfOperationsBaselineCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c2)
	c3, err := makeGroupOfOperationsCustomPocCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c3)
	c4, err := makeGroupOfOperationsDomainAssetCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c4)
	c5, err := makeGroupOfOperationsInsightCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c5)
	c6, err := makeGroupOfOperationsIPAssetCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c6)
	c7, err := makeGroupOfOperationsPlanCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c7)
	c8, err := makeGroupOfOperationsProjectCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c8)
	c9, err := makeGroupOfOperationsReportCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c9)
	c10, err := makeGroupOfOperationsResultCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c10)
	c11, err := makeGroupOfOperationsRoleCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c11)
	c12, err := makeGroupOfOperationsServiceAssetCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c12)
	c13, err := makeGroupOfOperationsSystemInfoCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c13)
	c14, err := makeGroupOfOperationsSystemServiceCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c14)
	c15, err := makeGroupOfOperationsTaskConfigCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c15)
	c16, err := makeGroupOfOperationsTemplateCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c16)
	c17, err := makeGroupOfOperationsUserCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c17)
	c18, err := makeGroupOfOperationsVulnerabilityCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c18)
	c19, err := makeGroupOfOperationsWebAssetCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c19)
	c20, err := makeGroupOfOperationsXprocessCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c20)
	c21, err := makeGroupOfOperationsXprocessLiteCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c21)

	// add cobra completion
	rootCmd.AddCommand(makeGenCompletionCmd())

	// add cobra markdown
	markdownCmd := makeMarkdownDocumentationCmd()
	rootCmd.AddCommand(markdownCmd)
	markdownCmd.Flags().String("dir", "./markdown/", "The destination directory to save docs in")
	_ = viper.BindPFlag("markdown_dir", markdownCmd.Flags().Lookup("dir"))

	return rootCmd, nil
}

// registerAuthInoWriterFlags registers all flags needed to perform authentication
func registerAuthInoWriterFlags(cmd *cobra.Command) error {
	cmd.PersistentFlags().String("api-key", "", "")
	return nil
}

// makeAuthInfoWriter retrieves cmd flags and construct an auth info writer
func makeAuthInfoWriter(cmd *cobra.Command) (runtime.ClientAuthInfoWriter, error) {
	auths := []runtime.ClientAuthInfoWriter{}

	token := resolveToken(cmd)
	if token != "" {
		auths = append(auths, httptransport.APIKeyAuth("token", "header", token))
	}

	if len(auths) == 0 {
		logDebugf("Warning: No auth params detected.")
		return nil, nil
	}

	// compose all auths together
	return httptransport.Compose(auths...), nil
}

func resolveServerConfig(cmd *cobra.Command) (string, string, string, error) {
	rawURL := runtimeCfg.URL
	if flagChanged(cmd, "url") {
		value, err := cmd.Flags().GetString("url")
		if err != nil {
			return "", "", "", err
		}
		rawURL = value
	}
	if rawURL == "" {
		return "", "", "", fmt.Errorf("xray url is not configured")
	}

	parsed, err := neturl.Parse(rawURL)
	if err != nil {
		return "", "", "", fmt.Errorf("parse xray url %q: %w", rawURL, err)
	}
	if parsed.Scheme == "" || parsed.Host == "" {
		return "", "", "", fmt.Errorf("invalid xray url %q", rawURL)
	}

	basePath := parsed.EscapedPath()
	if basePath == "" {
		basePath = client.DefaultBasePath
	}

	return parsed.Scheme, parsed.Host, basePath, nil
}

func resolveToken(cmd *cobra.Command) string {
	if flagChanged(cmd, "api-key") {
		token, err := cmd.Flags().GetString("api-key")
		if err == nil {
			return token
		}
	}
	return runtimeCfg.APIKey
}

func flagChanged(cmd *cobra.Command, name string) bool {
	flag := cmd.Flags().Lookup(name)
	return flag != nil && flag.Changed
}

func SetRuntimeConfig(cfg config.Raw, enabledDryRun bool) {
	productCfg, err := config.DecodeProduct[runtimeProductConfig](cfg, "xray")
	if err == nil {
		runtimeCfg = productCfg
	}
	dryRun = enabledDryRun
}

// makeGroupOfOperationsAssetPropertyCmd returns a parent command to handle all operations with tag "asset_property"
func makeGroupOfOperationsAssetPropertyCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "asset_property",
		Long: ``,
	}

	sub0, err := makeOperationAssetPropertyGetAssetGroupsProjectIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationAssetPropertyGetAssetTagIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationAssetPropertyGetBusinessSystemIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationAssetPropertyGetLocationIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationAssetPropertyGetNetworkRegionIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationAssetPropertyPostAssetTagFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationAssetPropertyPostBusinessSystemCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationAssetPropertyPostBusinessSystemFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	sub8, err := makeOperationAssetPropertyPostLocationFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub8)

	sub9, err := makeOperationAssetPropertyPostNetworkRegionCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub9)

	sub10, err := makeOperationAssetPropertyPostNetworkRegionFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub10)

	return parent, nil
} // makeGroupOfOperationsAuditLogCmd returns a parent command to handle all operations with tag "audit_log"
func makeGroupOfOperationsAuditLogCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "audit_log",
		Long: ``,
	}

	sub0, err := makeOperationAuditLogGetAuditlogActionCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationAuditLogPostAuditlogFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	return parent, nil
} // makeGroupOfOperationsBaselineCmd returns a parent command to handle all operations with tag "baseline"
func makeGroupOfOperationsBaselineCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "baseline",
		Long: ``,
	}

	sub0, err := makeOperationBaselinePostBaselineTaskCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationBaselinePostBaselineTaskExecuteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationBaselinePostBaselineTaskFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationBaselinePostBaselineTaskStopCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationBaselinePostCheckSetsFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationBaselinePostProcessItemFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationBaselinePostSSHKeyCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationBaselinePostSSHKeyFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	return parent, nil
} // makeGroupOfOperationsCustomPocCmd returns a parent command to handle all operations with tag "custom_poc"
func makeGroupOfOperationsCustomPocCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "custom_poc",
		Long: ``,
	}

	sub0, err := makeOperationCustomPocDeleteCustompocCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationCustomPocGetVulnCategoryCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationCustomPocPostCustompocCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationCustomPocPostCustompocFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationCustomPocPostCustompocUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationCustomPocPostCustomtagCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationCustomPocPostUploadCustompocCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	return parent, nil
} // makeGroupOfOperationsDomainAssetCmd returns a parent command to handle all operations with tag "domain_asset"
func makeGroupOfOperationsDomainAssetCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "domain_asset",
		Long: ``,
	}

	sub0, err := makeOperationDomainAssetDeleteDomainCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationDomainAssetGetDomainIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationDomainAssetPostDomainCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationDomainAssetPostDomainFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationDomainAssetPostDomainFilterSimpleCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationDomainAssetPostDomainIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	return parent, nil
} // makeGroupOfOperationsInsightCmd returns a parent command to handle all operations with tag "insight"
func makeGroupOfOperationsInsightCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "insight",
		Long: ``,
	}

	sub0, err := makeOperationInsightPostAPIV2InsightAssetDeletedIPListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationInsightPostInsightAssetIPAliveCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationInsightPostInsightAssetIPContinuingCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationInsightPostInsightAssetIPDeletedCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationInsightPostInsightAssetIPListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationInsightPostInsightAssetIPNewlyAddedCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationInsightPostInsightAssetIPRiskCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationInsightPostInsightAssetIPScannedCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	sub8, err := makeOperationInsightPostInsightAssetIPTotalCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub8)

	sub9, err := makeOperationInsightPostInsightVulnAvgFixPeriodCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub9)

	sub10, err := makeOperationInsightPostInsightVulnContinuingCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub10)

	sub11, err := makeOperationInsightPostInsightVulnListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub11)

	sub12, err := makeOperationInsightPostInsightVulnNewlyDiscoveredCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub12)

	sub13, err := makeOperationInsightPostInsightVulnRemediatedCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub13)

	sub14, err := makeOperationInsightPostInsightVulnTotalCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub14)

	sub15, err := makeOperationInsightPostInsightXprocessCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub15)

	sub16, err := makeOperationInsightPostInsightXprocessScannedAssetCountCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub16)

	return parent, nil
} // makeGroupOfOperationsIPAssetCmd returns a parent command to handle all operations with tag "ip_asset"
func makeGroupOfOperationsIPAssetCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "ip_asset",
		Long: ``,
	}

	sub0, err := makeOperationIPAssetDeleteIPCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationIPAssetGetIPIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationIPAssetGetIPOsCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationIPAssetPostIPCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationIPAssetPostIPFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationIPAssetPostIPIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	return parent, nil
} // makeGroupOfOperationsPlanCmd returns a parent command to handle all operations with tag "plan"
func makeGroupOfOperationsPlanCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "plan",
		Long: ``,
	}

	sub0, err := makeOperationPlanDeletePlanIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationPlanGetPlanIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationPlanPostPlanCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationPlanPostPlanExecuteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationPlanPostPlanFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationPlanPostPlanStopCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationPlanPostPlanUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationPlanCreateQuickCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	return parent, nil
} // makeGroupOfOperationsProjectCmd returns a parent command to handle all operations with tag "project"
func makeGroupOfOperationsProjectCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "project",
		Long: ``,
	}

	sub0, err := makeOperationProjectGetProjectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationProjectGetProjectIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationProjectPostProjectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationProjectPostProjectFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationProjectPostProjectIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	return parent, nil
} // makeGroupOfOperationsReportCmd returns a parent command to handle all operations with tag "report"
func makeGroupOfOperationsReportCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "report",
		Long: ``,
	}

	sub0, err := makeOperationReportDeleteReportIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationReportGetReportIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationReportPostReportCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationReportPostReportDownloadCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationReportPostReportFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationReportPostReportTemplateFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	return parent, nil
} // makeGroupOfOperationsResultCmd returns a parent command to handle all operations with tag "result"
func makeGroupOfOperationsResultCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "result",
		Long: ``,
	}

	sub0, err := makeOperationResultGetResultIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationResultPostResultFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	return parent, nil
} // makeGroupOfOperationsRoleCmd returns a parent command to handle all operations with tag "role"
func makeGroupOfOperationsRoleCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "role",
		Long: ``,
	}

	sub0, err := makeOperationRolePostRoleCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationRolePostRoleFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	return parent, nil
} // makeGroupOfOperationsServiceAssetCmd returns a parent command to handle all operations with tag "service_asset"
func makeGroupOfOperationsServiceAssetCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "service_asset",
		Long: ``,
	}

	sub0, err := makeOperationServiceAssetDeleteServiceCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationServiceAssetGetServiceApplicationProtocolCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationServiceAssetGetServiceIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationServiceAssetPostServiceCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationServiceAssetPostServiceFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationServiceAssetPostServiceIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	return parent, nil
} // makeGroupOfOperationsSystemInfoCmd returns a parent command to handle all operations with tag "system_info"
func makeGroupOfOperationsSystemInfoCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "system_info",
		Long: ``,
	}

	sub0, err := makeOperationSystemInfoDeleteEngineIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationSystemInfoGetSystemDNSEngineIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationSystemInfoGetSystemHostsEngineIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationSystemInfoGetSystemInfoEngineIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationSystemInfoGetSystemInfoMgmtCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationSystemInfoGetSystemInfoServicesCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationSystemInfoGetVulnLibraryInfoCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationSystemInfoPostSystemDNSEngineIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	sub8, err := makeOperationSystemInfoPostSystemHostsEngineIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub8)

	sub9, err := makeOperationSystemInfoPostSystemInfoServicesCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub9)

	return parent, nil
} // makeGroupOfOperationsSystemServiceCmd returns a parent command to handle all operations with tag "system_service"
func makeGroupOfOperationsSystemServiceCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "system_service",
		Long: ``,
	}

	sub0, err := makeOperationSystemServicePostEngineUpgradeCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationSystemServicePostExecutionFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationSystemServicePostPackageCheckCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationSystemServicePostSystemLicenseCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationSystemServicePostUploadUpgradePackageCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationSystemServicePostVulnLibraryUpgradeCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	return parent, nil
} // makeGroupOfOperationsTaskConfigCmd returns a parent command to handle all operations with tag "task_config"
func makeGroupOfOperationsTaskConfigCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "task_config",
		Long: ``,
	}

	sub0, err := makeOperationTaskConfigDeleteScannerdictCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationTaskConfigDeleteWhitelistCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationTaskConfigGetCustomPluginIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationTaskConfigGetReversePlatformUUIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationTaskConfigGetScannerdictIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationTaskConfigGetWhitelistIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationTaskConfigPostCustomPluginFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationTaskConfigPostEngineFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	sub8, err := makeOperationTaskConfigPostHostCredentialCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub8)

	sub9, err := makeOperationTaskConfigPostHostCredentialVerifyCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub9)

	sub10, err := makeOperationTaskConfigPostHostlogruleFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub10)

	sub11, err := makeOperationTaskConfigPostPluginFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub11)

	sub12, err := makeOperationTaskConfigPostPortgroupFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub12)

	sub13, err := makeOperationTaskConfigPostReversePlatformFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub13)

	sub14, err := makeOperationTaskConfigPostScannerdictCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub14)

	sub15, err := makeOperationTaskConfigPostScannerdictFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub15)

	sub16, err := makeOperationTaskConfigPostUploadFileCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub16)

	sub17, err := makeOperationTaskConfigPostWhitelistCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub17)

	sub18, err := makeOperationTaskConfigPostWhitelistFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub18)

	sub19, err := makeOperationTaskConfigPostWhitelistUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub19)

	return parent, nil
} // makeGroupOfOperationsTemplateCmd returns a parent command to handle all operations with tag "template"
func makeGroupOfOperationsTemplateCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "template",
		Long: ``,
	}

	sub0, err := makeOperationTemplateGetTemplateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationTemplateGetTemplateIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationTemplateGetTemplateSummaryCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	return parent, nil
} // makeGroupOfOperationsUserCmd returns a parent command to handle all operations with tag "user"
func makeGroupOfOperationsUserCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "user",
		Long: ``,
	}

	sub0, err := makeOperationUserDeleteUserIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationUserPostAccountChangeSelfPasswdCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationUserPostAccountChangeSomeonePasswdWithoutTokenCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationUserPostAccountResetUserPasswdCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationUserPostUserCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationUserPostUserFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationUserPostUserIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationUserPostUserTokenRefreshCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	return parent, nil
} // makeGroupOfOperationsVulnerabilityCmd returns a parent command to handle all operations with tag "vulnerability"
func makeGroupOfOperationsVulnerabilityCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "vulnerability",
		Long: ``,
	}

	sub0, err := makeOperationVulnerabilityDeleteVulnCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationVulnerabilityGetVulnIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationVulnerabilityGetVulnRetestTaskIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationVulnerabilityPostAPIV2VulnRetestBatchResultCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationVulnerabilityPostVulnBatchUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationVulnerabilityPostVulnFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationVulnerabilityPostVulnIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationVulnerabilityPostVulnRetestCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	sub8, err := makeOperationVulnerabilityPostVulnRetestBatchCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub8)

	sub9, err := makeOperationVulnerabilityPostVulnerabilityAverageFixTimeCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub9)

	return parent, nil
} // makeGroupOfOperationsWebAssetCmd returns a parent command to handle all operations with tag "web_asset"
func makeGroupOfOperationsWebAssetCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "web_asset",
		Long: ``,
	}

	sub0, err := makeOperationWebAssetDeleteWebsiteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationWebAssetGetWebsiteIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationWebAssetGetWebsiteOpenapiIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationWebAssetPostWebsiteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationWebAssetPostWebsiteFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationWebAssetPostWebsiteFilterSimpleCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationWebAssetPostWebsiteIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	return parent, nil
} // makeGroupOfOperationsXprocessCmd returns a parent command to handle all operations with tag "xprocess"
func makeGroupOfOperationsXprocessCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "xprocess",
		Long: ``,
	}

	sub0, err := makeOperationXprocessGetXprocessIDCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationXprocessGetXprocessIDInfoCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationXprocessGetXprocessIDProgressCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationXprocessPostXprocessFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationXprocessPostXprocessPauseCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationXprocessPostXprocessPauseStageCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationXprocessPostXprocessResumeCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationXprocessPostXprocessResumeStageCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	sub8, err := makeOperationXprocessPostXprocessStopCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub8)

	return parent, nil
} // makeGroupOfOperationsXprocessLiteCmd returns a parent command to handle all operations with tag "xprocess_lite"
func makeGroupOfOperationsXprocessLiteCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "xprocess_lite",
		Long: ``,
	}

	sub0, err := makeOperationXprocessLitePostXprocessLiteFilterCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	return parent, nil
}
